// packages/solid/src/hooks/accounts/useAccount.tsx
import type { GetAccountResult, Provider } from '@wagmi/core'
import { getAccount, watchAccount } from '@wagmi/core'
import { createEffect, createSignal, onCleanup } from 'solid-js'

export type UseAccountConfig = {
  /** Function to invoke when connected */
  onConnect?({
    address,
    connector,
    isReconnected,
  }: {
    address?: GetAccountResult['address']
    connector?: GetAccountResult['connector']
    isReconnected: boolean
  }): void
  /** Function to invoke when disconnected */
  onDisconnect?(): void
}

export const useAccount = (props?: UseAccountConfig) => {
  const [account, setAccount] = createSignal<GetAccountResult<Provider>>(
    getAccount(),
  )

  createEffect(() => {
    const unsubscribe = watchAccount((result) => {
      const prevStatus = account().status

      setAccount(result)

      if (
        props?.onConnect &&
        prevStatus !== 'connected' &&
        result.status === 'connected'
      ) {
        props.onConnect({
          address: account()?.address,
          connector: account()?.connector,
          isReconnected: prevStatus === 'reconnecting',
        })
      }

      if (
        props?.onDisconnect &&
        prevStatus === 'connected' &&
        result.status === 'disconnected'
      ) {
        props.onDisconnect()
      }
    })
    onCleanup(unsubscribe)
  })

  return account
}

// packages/react/src/hooks/accounts/useAccount.ts
import type { GetAccountResult } from '@wagmi/core'
import { getAccount, watchAccount } from '@wagmi/core'
import * as React from 'react'

import { useSyncExternalStoreWithTracked } from '../utils'

export type UseAccountConfig = {
  /** Function to invoke when connected */
  onConnect?({
    address,
    connector,
    isReconnected,
  }: {
    address?: GetAccountResult['address']
    connector?: GetAccountResult['connector']
    isReconnected: boolean
  }): void
  /** Function to invoke when disconnected */
  onDisconnect?(): void
}

export function useAccount({ onConnect, onDisconnect }: UseAccountConfig = {}) {
  const account = useSyncExternalStoreWithTracked(watchAccount, getAccount)
  const previousAccountRef = React.useRef<typeof account>()
  const previousAccount: Partial<typeof account> =
    previousAccountRef.current ?? {}

  React.useEffect(() => {
    if (
      previousAccount.status !== 'connected' &&
      account.status === 'connected'
    ) {
      onConnect?.({
        address: account.address,
        connector: account.connector,
        isReconnected:
          previousAccount.status === 'reconnecting' ||
          // when `previousAccount.status` is `undefined`, it means connector connected immediately
          previousAccount.status === undefined,
      })
    }

    if (
      previousAccount.status === 'connected' &&
      account.status === 'disconnected'
    ) {
      onDisconnect?.()
    }

    previousAccountRef.current = account
  }, [onConnect, onDisconnect, previousAccount, account])

  return account
}
