// packages/react/src/hooks/providers/useWebSocketProvider.ts
import { providers } from 'ethers'
import {
  GetWebSocketProviderArgs,
  getWebSocketProvider,
  watchWebSocketProvider,
} from '@wagmi/core'
import * as React from 'react'

import { useClient } from '../../context'
import { useForceUpdate } from '../utils'

export type UseWebSocketProviderArgs = Partial<GetWebSocketProviderArgs>

export function useWebSocketProvider<
  TWebSocketProvider extends providers.WebSocketProvider,
>({ chainId }: UseWebSocketProviderArgs = {}) {
  const forceUpdate = useForceUpdate()
  const client = useClient()
  const webSocketProvider = React.useRef(
    getWebSocketProvider<TWebSocketProvider>({ chainId }),
  )

  React.useEffect(() => {
    const unwatch = watchWebSocketProvider<TWebSocketProvider>(
      { chainId },
      (webSocketProvider_) => {
        webSocketProvider.current = webSocketProvider_
        forceUpdate()
      },
    )
    return unwatch
  }, [chainId, client, forceUpdate])

  return webSocketProvider.current
}

// packages/solid/src/hooks/providers/useWebSocketProvider.ts
import type { WebSocketProvider } from '@wagmi/core'
import { getWebSocketProvider, watchWebSocketProvider } from '@wagmi/core'
import type { Accessor } from 'solid-js'
import { createEffect, createMemo, createSignal, onCleanup } from 'solid-js'

export type GetWebSocketProviderArgs = {
  chainId?: Accessor<number> | undefined
}

export type UseWebSocketProviderArgs = Partial<GetWebSocketProviderArgs>

export function useWebSocketProvider(props?: UseWebSocketProviderArgs) {
  const [webSocketProvider, setWebSocketProvider] =
    createSignal<WebSocketProvider>()

  const args = createMemo(() =>
    props?.chainId ? { chainId: props.chainId() } : {},
  )

  setWebSocketProvider(getWebSocketProvider(args()))

  createEffect(() => {
    const unsubscribe = watchWebSocketProvider(args(), (webSocketProvider) =>
      setWebSocketProvider(webSocketProvider),
    )
    onCleanup(() => unsubscribe())
  })

  return webSocketProvider
}
