// packages/svelte/src/routes/_components/BlockNumber.svelte
<script>
import { useBlockNumber } from '$lib/hooks/useBlockNumber.svelte'
import { optimism } from 'viem/chains'

const defaultBlock = $derived.by(useBlockNumber(() => ({ watch: true })))
const accountBlock = $derived.by(useBlockNumber(() => ({ watch: true })))
const optimismBlock = $derived.by(
  useBlockNumber(() => ({ chainId: optimism.id, watch: true })),
)
</script>

<h2>Block Number</h2>

<div>Block Number (Default Chain): {defaultBlock.data?.toString()}</div>
<div>Block Number (Account Chain): {accountBlock.data?.toString()}</div>
<div>Block Number (Optimism): {optimismBlock.data?.toString()}</div>

// playgrounds/vite-solid/src/components/BlockNumber.tsx
import { useBlockNumber } from '@wagmi/solid'
import { optimism } from '@wagmi/solid/chains'

export function BlockNumber() {
  const default_ = useBlockNumber(() => ({ watch: true }))
  const account_ = useBlockNumber(() => ({ watch: true }))
  const optimism_ = useBlockNumber(() => ({
    chainId: optimism.id,
    watch: true,
  }))

  return (
    <div>
      <h2>Block Number</h2>

      <div>Block Number (Default Chain): {default_.data?.toString()}</div>
      <div>Block Number (Connection Chain): {account_.data?.toString()}</div>
      <div>Block Number (Optimism): {optimism_.data?.toString()}</div>
    </div>
  )
}
