// playgrounds/vite-vue/src/components/BlockNumber.vue
<script setup lang="ts">
import { useBlockNumber } from '@wagmi/vue'
import { ref } from 'vue'

const watchBlockNumber = ref(false)

const { data: blockNumber } = useBlockNumber({ watch: watchBlockNumber })
</script>

<template>
  <h2>Block Number</h2>

  <div>{{ blockNumber }}</div>
  <button type="button" @click="watchBlockNumber = !watchBlockNumber">
    {{ watchBlockNumber ? 'Stop' : 'Start' }} watching
  </button>
</template>

// playgrounds/vite-solid/src/components/BlockNumber.tsx
import { useBlockNumber } from '@wagmi/solid'
import { optimism } from '@wagmi/solid/chains'

export function BlockNumber() {
  const default_ = useBlockNumber(() => ({ watch: true }))
  const account_ = useBlockNumber(() => ({ watch: true }))
  const optimism_ = useBlockNumber(() => ({
    chainId: optimism.id,
    watch: true,
  }))

  return (
    <div>
      <h2>Block Number</h2>

      <div>Block Number (Default Chain): {default_.data?.toString()}</div>
      <div>Block Number (Connection Chain): {account_.data?.toString()}</div>
      <div>Block Number (Optimism): {optimism_.data?.toString()}</div>
    </div>
  )
}
