// playgrounds/vite-vue/src/components/SendTransaction.vue
<script setup lang="ts">
import { Hex, parseEther } from 'viem'
import { useSendTransaction } from '@wagmi/vue'

const {
  data: hash,
  error,
  isPending,
  sendTransaction
} = useSendTransaction()

function onSubmit(event: any) {
  const form = new FormData(event.target)
  const to = form.get('address')! as Hex
  const value = parseEther(form.get('value') as string)
  sendTransaction({ to, value })
}
</script>

<template>
  <h2>
    Send Transaction
  </h2>
  <form @submit.prevent="onSubmit">
    <input name="address" placeholder="Address" required />
    <input name="value" placeholder="Amount (ETH)" type="number" step="0.000000001" required />
    <button type="submit">
      Send
    </button>
  </form>
  <div v-if="isPending">
    Sending...
  </div>
  <div v-if="hash">
    Hash: {{ hash }}
  </div>
  <div v-if="error">
    Error: {{ error.message }}
  </div>
</template>

// packages/svelte/src/routes/_components/SendTransaction.svelte
<script lang="ts">
import { BaseError } from '$lib/errors.js'
import { useSendTransaction } from '$lib/hooks/useSendTransaction.svelte.js'
import { useWaitForTransactionReceipt } from '$lib/hooks/useWaitForTransactionReceipt.svelte.js'
import { type Hex, parseEther } from 'viem'

const {
  data: hash,
  error,
  isPending,
  sendTransaction,
} = $derived.by(useSendTransaction())

async function submit(e: SubmitEvent) {
  e.preventDefault()
  const formData = new FormData(e.target as HTMLFormElement)
  const to = formData.get('address') as Hex
  const value = formData.get('value') as string
  sendTransaction({ to, value: parseEther(value) })
}

const { isLoading: isConfirming, isSuccess: isConfirmed } = $derived.by(
  useWaitForTransactionReceipt(() => ({
    hash,
  })),
)
</script>

<div>
	<h2>Send Transaction</h2>
	<form onsubmit={submit}>
		<input name="address" placeholder="Address" required />
		<input name="value" placeholder="Amount (ETH)" type="number" step="0.000000001" required />
		<button disabled={isPending} type="submit">
			{isPending ? 'Confirming...' : 'Send'}
		</button>
	</form>
	{#if hash}
		<div>Transaction Hash: {hash}</div>
	{/if}
	{#if isConfirming}
		Waiting for confirmation...
	{/if}
	{#if isConfirmed}
		Transaction confirmed.
	{/if}
	{#if error}
		<div>Error: {(error as BaseError).shortMessage || error.message}</div>
	{/if}
</div>
