// playgrounds/solid-start/src/components/SwitchChain.tsx
import { useChainId, useChains, useSwitchChain } from '@wagmi/solid'
import { For } from 'solid-js'

export function SwitchChain() {
  const chainId = useChainId()
  const switchChain = useSwitchChain()
  const chains = useChains()

  return (
    <div>
      <h2>Switch Chain</h2>

      <For each={chains()}>
        {(chain) => (
          <button
            disabled={chainId() === chain.id}
            onClick={() => switchChain.mutate({ chainId: chain.id })}
            type="button"
          >
            {chain.name}
          </button>
        )}
      </For>

      {switchChain.error?.message}
    </div>
  )
}

// packages/svelte/src/routes/_components/SwitchChain.svelte
<script lang="ts">
import { useChainId } from '$lib/hooks/useChainId.svelte.js'
import { useSwitchChain } from '$lib/hooks/useSwitchChain.svelte.js'

const chainId = $derived.by(useChainId())
const { chains, switchChain, error } = $derived.by(useSwitchChain())
</script>

<h2>Switch Chain</h2>

{#each chains as chain}
	<button
		disabled={chainId === chain.id}
		onclick={() => switchChain({ chainId: chain.id })}
		type="button"
	>
		{chain.name}
	</button>
{/each}

{#if error}
	{error.message}
{/if}
