// packages/create-wagmi/templates/next/src/app/page.tsx
'use client'

import { useConnect, useConnection, useConnectors, useDisconnect } from 'wagmi'

function App() {
  const connection = useConnection()
  const { connectors, connect, status, error } = useConnect()
  const connectors = useConnectors()
  const { disconnect } = useDisconnect()

  return (
    <>
      <div>
        <h2>Connection</h2>

        <div>
          status: {connection.status}
          <br />
          addresses: {JSON.stringify(connection.addresses)}
          <br />
          chainId: {connection.chainId}
        </div>

        {connection.status === 'connected' && (
          <button type="button" onClick={() => disconnect()}>
            Disconnect
          </button>
        )}
      </div>

      <div>
        <h2>Connect</h2>
        {connectors.map((connector) => (
          <button
            key={connector.uid}
            onClick={() => connect({ connector })}
            type="button"
          >
            {connector.name}
          </button>
        ))}
        <div>{status}</div>
        <div>{error?.message}</div>
      </div>
    </>
  )
}

export default App

// playgrounds/devtools/src/App.tsx
import {
  useAccount,
  useChainId,
  useConnect,
  useConnections,
  useConnectors,
  useDisconnect,
} from '@wagmi/solid'
import { For } from 'solid-js'

export function App() {
  return (
    <>
      <Account />
      <Connect />
      {/* <SwitchAccount /> */}
      {/* <SwitchChain /> */}
      <Connections />
    </>
  )
}

function Account() {
  const account = useAccount()
  const disconnect = useDisconnect()

  return (
    <div>
      <h2>Account</h2>

      <div>
        account: {account.address}
        <br />
        chainId: {account.chainId}
        <br />
        status: {account.status}
      </div>

      {account.status !== 'disconnected' && (
        <button type="button" onClick={() => disconnect.mutate({})}>
          Disconnect
        </button>
      )}
    </div>
  )
}

function Connect() {
  const chainId = useChainId()
  const connect = useConnect()
  const connectors = useConnectors()

  return (
    <div>
      <h2>Connect</h2>
      <For each={connectors}>
        {(connector) => (
          <button
            onClick={() => connect.mutate({ connector, chainId })}
            type="button"
          >
            {connector.name}
          </button>
        )}
      </For>
      <div>{connect.status}</div>
      <div>{connect.error?.message}</div>
    </div>
  )
}

function Connections() {
  const connections = useConnections()

  return (
    <div>
      <h2>Connections</h2>

      <For each={connections}>
        {(connection) => (
          <div>
            <div>connector {connection.connector.name}</div>
            <div>accounts: {JSON.stringify(connection.accounts)}</div>
            <div>chainId: {connection.chainId}</div>
          </div>
        )}
      </For>
    </div>
  )
}
