// playgrounds/vite-vue/src/App.vue
<script setup lang="ts">
  import { useAccount, useConnect, useDisconnect } from '@wagmi/vue'

  const account = useAccount()
  const connect = useConnect()
  const disconnect = useDisconnect()
</script>

<template>
  <div>
    <div>
      <h2>Account</h2>

      <div>
        account: {{ account.address }}
        <br />
        chainId: {{ account.chainId }}
        <br />
        status: {{ account.status }}
      </div>

      <button
        v-if="account.status !== 'disconnected'"
        type="button"
        @click="disconnect.disconnect()"
      >
        Disconnect
      </button>
    </div>

    <div>
      <h2>Connect</h2>

      <button
        v-for="connector in connect.connectors"
        :key="connector.id"
        type="button"
        @click="connect.connect({ connector })"
      >
        {{ connector.name }}
      </button>

      <div>{{ connect.status }}</div>
      <div>{{ connect.error }}</div>
    </div>
  </div>
</template>

// playgrounds/devtools/src/App.tsx
import {
  useAccount,
  useChainId,
  useConnect,
  useConnections,
  useConnectors,
  useDisconnect,
} from '@wagmi/solid'
import { For } from 'solid-js'

export function App() {
  return (
    <>
      <Account />
      <Connect />
      {/* <SwitchAccount /> */}
      {/* <SwitchChain /> */}
      <Connections />
    </>
  )
}

function Account() {
  const account = useAccount()
  const disconnect = useDisconnect()

  return (
    <div>
      <h2>Account</h2>

      <div>
        account: {account.address}
        <br />
        chainId: {account.chainId}
        <br />
        status: {account.status}
      </div>

      {account.status !== 'disconnected' && (
        <button type="button" onClick={() => disconnect.mutate({})}>
          Disconnect
        </button>
      )}
    </div>
  )
}

function Connect() {
  const chainId = useChainId()
  const connect = useConnect()
  const connectors = useConnectors()

  return (
    <div>
      <h2>Connect</h2>
      <For each={connectors}>
        {(connector) => (
          <button
            onClick={() => connect.mutate({ connector, chainId })}
            type="button"
          >
            {connector.name}
          </button>
        )}
      </For>
      <div>{connect.status}</div>
      <div>{connect.error?.message}</div>
    </div>
  )
}

function Connections() {
  const connections = useConnections()

  return (
    <div>
      <h2>Connections</h2>

      <For each={connections}>
        {(connection) => (
          <div>
            <div>connector {connection.connector.name}</div>
            <div>accounts: {JSON.stringify(connection.accounts)}</div>
            <div>chainId: {connection.chainId}</div>
          </div>
        )}
      </For>
    </div>
  )
}
