// packages/react/src/hooks/accounts/useBalance.ts
import * as React from 'react'
import { FetchBalanceArgs, FetchBalanceResult, fetchBalance } from '@wagmi/core'
import { useQuery } from 'react-query'

import { QueryConfig, QueryFunctionArgs } from '../../types'
import { useBlockNumber } from '../network-status'
import { useChainId } from '../utils'

export type UseBalanceArgs = Partial<FetchBalanceArgs> & {
  /** Subscribe to changes */
  watch?: boolean
}

export type UseBalanceConfig = QueryConfig<FetchBalanceResult, Error>

export const queryKey = ({
  addressOrName,
  chainId,
  formatUnits,
  token,
}: Partial<FetchBalanceArgs> & {
  chainId?: number
}) =>
  [{ entity: 'balance', addressOrName, chainId, formatUnits, token }] as const

const queryFn = ({
  queryKey: [{ addressOrName, chainId, formatUnits, token }],
}: QueryFunctionArgs<typeof queryKey>) => {
  if (!addressOrName) throw new Error('address is required')
  return fetchBalance({ addressOrName, chainId, formatUnits, token })
}

export function useBalance({
  addressOrName,
  cacheTime,
  chainId: chainId_,
  enabled = true,
  formatUnits = 'ether',
  staleTime,
  suspense,
  token,
  watch,
  onError,
  onSettled,
  onSuccess,
}: UseBalanceArgs & UseBalanceConfig = {}) {
  const chainId = useChainId({ chainId: chainId_ })
  const balanceQuery = useQuery(
    queryKey({ addressOrName, chainId, formatUnits, token }),
    queryFn,
    {
      cacheTime,
      enabled: Boolean(enabled && addressOrName),
      staleTime,
      suspense,
      onError,
      onSettled,
      onSuccess,
    },
  )

  const { data: blockNumber } = useBlockNumber({ watch })
  React.useEffect(() => {
    if (!enabled) return
    if (!watch) return
    if (!blockNumber) return
    if (!addressOrName) return
    balanceQuery.refetch()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [blockNumber])

  return balanceQuery
}

// packages/solid/src/hooks/accounts/useBalance.tsx
import { createQuery } from '@tanstack/solid-query'
import type { Address, FetchBalanceResult } from '@wagmi/core'
import { fetchBalance } from '@wagmi/core'
import type { Accessor } from 'solid-js'
import { createMemo } from 'solid-js'

import type { QueryConfig, QueryFunctionArgs } from '../../types'

import { useAccount } from './useAccount'
import { useNetwork } from './useNetwork'

export type UseBalanceArgs = Partial<{
  address: Accessor<Address>
  chainId?: Accessor<number>
  formatUnits?: Accessor<
    | number
    | 'wei'
    | 'kwei'
    | 'mwei'
    | 'gwei'
    | 'szabo'
    | 'finney'
    | 'ether'
    | undefined
  >
  token?: Accessor<Address>
}> & {
  /** Subscribe to changes */
  watch?: boolean
}

export type UseBalanceConfig = QueryConfig<FetchBalanceResult, Error>

type QueryKeyArgs = Partial<UseBalanceArgs>
type QueryKeyConfig = Pick<UseBalanceConfig, 'scopeKey'>

function queryKey(props: QueryKeyArgs & QueryKeyConfig) {
  return [
    {
      entity: 'balance',
      address: props.address?.(),
      chainId: props.chainId?.(),
      formatUnits: props.formatUnits?.(),
      scopeKey: props.scopeKey,
      token: props.token?.(),
    } as const,
  ]
}

function queryFn({
  queryKey: [{ address, chainId, formatUnits, token }],
}: QueryFunctionArgs<typeof queryKey>) {
  if (!address) throw new Error('address is required')
  return fetchBalance({
    address,
    chainId,
    formatUnits,
    token,
  })
}

export const useBalance = (props?: UseBalanceArgs & UseBalanceConfig) => {
  const accountData = useAccount()
  const networkData = useNetwork()

  const address = createMemo(() => props?.address?.() ?? accountData().address)
  const chainId = createMemo(
    () => props?.chainId?.() ?? networkData()?.chain?.id,
  )

  const queryKey = createMemo(() => {
    return {
      scopeKey: props?.scopeKey,
      entity: 'balance',
      chainId: chainId(),
      address: address(),
    }
  })

  const balanceQuery = createQuery(() => [queryKey()], queryFn, {
    get enabled() {
      return Boolean(address() && chainId())
    },
    ...{
      staleTime: props?.staleTime,
      suspense: props?.suspense,
      onError: props?.onError,
      onSettled: props?.onSettled,
      onSucces: props?.onSuccess,
    },
  })

  // TODO: implement this when other hooks are done.

  // useInvalidateOnBlock({
  //   chainId,
  //   enabled: Boolean(props.enabled() && props.watch() && address()),
  //   queryKey: queryKey(),
  // })

  return balanceQuery
}
