// packages/react/src/hooks/accounts/useConnect.ts
import * as React from 'react'
import { ConnectArgs, ConnectResult, Connector, connect } from '@wagmi/core'
import { UseMutationOptions, UseMutationResult, useMutation } from 'react-query'

import { useClient } from '../../context'
import { useForceUpdate } from '../utils'

export type UseConnectArgs = Partial<ConnectArgs>

type MutationOptions = UseMutationOptions<ConnectResult, Error, ConnectArgs>
export type UseConnectConfig = {
  /** Chain to connect */
  chainId?: number
  /**
   * Function to invoke before connect and is passed same variables connect function would receive.
   * Value returned from this function will be passed to both onError and onSettled functions in event of a mutation failure.
   */
  onBeforeConnect?: MutationOptions['onMutate']
  /** Function to invoke when connect is successful. */
  onConnect?: MutationOptions['onSuccess']
  /** Function to invoke when an error is thrown while connecting. */
  onError?: MutationOptions['onError']
  /** Function to invoke when connect is settled (either successfully connected, or an error has thrown). */
  onSettled?: MutationOptions['onSettled']
}

export const mutationKey = (args: UseConnectArgs) => [
  { entity: 'connect', ...args },
]

const mutationFn = (args: UseConnectArgs) => {
  const { connector, chainId } = args
  if (!connector) throw new Error('connector is required')
  return connect({ connector, chainId })
}

export function useConnect({
  chainId,
  connector,
  onBeforeConnect,
  onConnect,
  onError,
  onSettled,
}: UseConnectArgs & UseConnectConfig = {}) {
  const forceUpdate = useForceUpdate()
  const client = useClient()

  const { data, error, mutate, mutateAsync, reset, status, variables } =
    useMutation(mutationKey({ connector, chainId }), mutationFn, {
      onError,
      onMutate: onBeforeConnect,
      onSettled,
      onSuccess: onConnect,
    })

  React.useEffect(() => {
    // Trigger update when connector or status change
    const unsubscribe = client.subscribe(
      (state) => ({
        connector: state.connector,
        connectors: state.connectors,
        status: state.status,
      }),
      forceUpdate,
      {
        equalityFn: (selected, previous) =>
          selected.connector === previous.connector &&
          selected.connectors === previous.connectors &&
          selected.status === previous.status,
      },
    )
    return unsubscribe
  }, [client, forceUpdate])

  const connect = React.useCallback(
    (connectorOrArgs?: Partial<ConnectArgs> | ConnectArgs['connector']) => {
      let config: Partial<ConnectArgs>
      if (connectorOrArgs instanceof Connector) {
        const connector_ = connectorOrArgs
        config = {
          chainId,
          connector: connector_ ?? connector,
        }
      } else {
        const args = connectorOrArgs
        config = {
          chainId: args?.chainId ?? chainId,
          connector: args?.connector ?? connector,
        }
      }
      return mutate(<ConnectArgs>config)
    },
    [chainId, connector, mutate],
  )

  const connectAsync = React.useCallback(
    (connectorOrArgs?: Partial<ConnectArgs> | ConnectArgs['connector']) => {
      let config: Partial<ConnectArgs>
      if (connectorOrArgs instanceof Connector) {
        const connector_ = connectorOrArgs
        config = {
          chainId,
          connector: connector_ ?? connector,
        }
      } else {
        const args = connectorOrArgs
        config = {
          chainId: args?.chainId ?? chainId,
          connector: args?.connector ?? connector,
        }
      }
      return mutateAsync(<ConnectArgs>config)
    },
    [chainId, connector, mutateAsync],
  )

  let status_:
    | Extract<UseMutationResult['status'], 'error' | 'idle'>
    | 'connected'
    | 'connecting'
    | 'disconnected'
    | 'reconnecting'
  if (client.status === 'reconnecting') status_ = 'reconnecting'
  else if (status === 'loading' || client.status === 'connecting')
    status_ = 'connecting'
  else if (client.connector) status_ = 'connected'
  else if (!client.connector || status === 'success') status_ = 'disconnected'
  else status_ = status

  return {
    activeConnector: client.connector,
    connect,
    connectAsync,
    connectors: client.connectors,
    data,
    error,
    isConnected: status_ === 'connected',
    isConnecting: status_ === 'connecting',
    isDisconnected: status_ === 'disconnected',
    isError: status === 'error',
    isIdle: status_ === 'idle',
    isReconnecting: status_ === 'reconnecting',
    pendingConnector: variables?.connector,
    reset,
    status: status_,
  } as const
}

// packages/solid/src/hooks/accounts/useConnect.tsx
import { createMutation } from '@tanstack/solid-query'
import { connect as _connect } from '@wagmi/core'
import type { ConnectResult, Connector } from '@wagmi/core'
import type { Accessor } from 'solid-js'

import { useClient } from '../../context'
import type { MutationConfig } from '../../types'

export type ConnectArgs = {
  chainId?: Accessor<number>
  connector?: Connector<any, any, any>
}

export type UseConnectArgs = Partial<ConnectArgs>
export type UseConnectConfig = MutationConfig<ConnectResult, Error, ConnectArgs>

export const mutationKey = (args: UseConnectArgs) =>
  [
    {
      entity: 'connect',
      chainId: args?.chainId?.(),
      connector: args.connector,
    },
  ] as const

const mutationFn = (args: UseConnectArgs) => {
  if (!args.connector) throw new Error('connector is required')
  return _connect({ chainId: args?.chainId?.(), connector: args.connector })
}

export const useConnect = (props?: UseConnectArgs & UseConnectConfig) => {
  const client = useClient()

  const {
    data,
    error,
    isError,
    isIdle,
    isLoading,
    isSuccess,
    mutate,
    mutateAsync,
    reset,
    status,
    variables,
  } = createMutation(
    mutationKey({
      chainId: props?.chainId,
      connector: props?.connector,
    }),
    mutationFn,
    {
      onError: props?.onError,
      onMutate: props?.onMutate,
      onSettled: props?.onSettled,
      onSuccess: props?.onSuccess,
    },
  )

  const connect = (args?: Partial<ConnectArgs>) =>
    mutate({
      chainId: args?.chainId ?? props?.chainId,
      connector: args?.connector ?? (props?.connector || client.connectors[0]),
    })

  const connectAsync = (args?: Partial<ConnectArgs>) => {
    return mutateAsync({
      chainId: args?.chainId ?? props?.chainId,
      connector: args?.connector ?? props?.connector,
    })
  }

  return {
    connect,
    connectAsync,
    connectors: client.connectors,
    data,
    error,
    isError,
    isIdle,
    isLoading,
    isSuccess,
    pendingConnector: variables?.connector,
    reset,
    status,
    variables,
  } as const
}
