// packages/react/src/hooks/accounts/useSignMessage.ts
import { SignMessageArgs, SignMessageResult, signMessage } from '@wagmi/core'
import * as React from 'react'

import { MutationConfig } from '../../types'
import { useMutation } from '../utils'

export type UseSignMessageArgs = Partial<SignMessageArgs>

export type UseSignMessageConfig = MutationConfig<
  SignMessageResult,
  Error,
  SignMessageArgs
>

export const mutationKey = (args: UseSignMessageArgs) =>
  [{ entity: 'signMessage', ...args }] as const

const mutationFn = (args: UseSignMessageArgs) => {
  const { message } = args
  if (!message) throw new Error('message is required')
  return signMessage({ message })
}

export function useSignMessage({
  message,
  onError,
  onMutate,
  onSettled,
  onSuccess,
}: UseSignMessageArgs & UseSignMessageConfig = {}) {
  const {
    data,
    error,
    isError,
    isIdle,
    isLoading,
    isSuccess,
    mutate,
    mutateAsync,
    reset,
    status,
    variables,
  } = useMutation(mutationKey({ message }), mutationFn, {
    onError,
    onMutate,
    onSettled,
    onSuccess,
  })

  const signMessage = React.useCallback(
    (args?: SignMessageArgs) => mutate(args || <SignMessageArgs>{ message }),
    [message, mutate],
  )

  const signMessageAsync = React.useCallback(
    (args?: SignMessageArgs) =>
      mutateAsync(args || <SignMessageArgs>{ message }),
    [message, mutateAsync],
  )

  return {
    data,
    error,
    isError,
    isIdle,
    isLoading,
    isSuccess,
    reset,
    signMessage,
    signMessageAsync,
    status,
    variables,
  }
}

// packages/solid/src/hooks/accounts/useSignMessage.tsx
import { createMutation } from '@tanstack/solid-query'
import type { SignMessageResult } from '@wagmi/core'
import { signMessage } from '@wagmi/core'
import type { Accessor } from 'solid-js'

import type { MutationConfig } from '../../types'

export type SignMessageArgs = {
  message: Accessor<string | Uint8Array>
}

export type UseSignMessageArgs = Partial<SignMessageArgs>

export type UseSignMessageConfig = MutationConfig<
  SignMessageResult,
  Error,
  SignMessageArgs
>

export const mutationKey = (args: UseSignMessageArgs) =>
  [{ entity: 'signMessage', ...args }] as const

const mutationFn = (args: UseSignMessageArgs) => {
  if (!args.message) throw new Error('message is required')
  return signMessage({ message: args.message() })
}

export const useSignMessage = (
  props?: UseSignMessageArgs & UseSignMessageConfig,
) => {
  const {
    data,
    error,
    isError,
    isIdle,
    isLoading,
    isSuccess,
    mutate,
    mutateAsync,
    reset,
    status,
    variables,
  } = createMutation(mutationKey({ message: props?.message }), mutationFn, {
    onError: props?.onError,
    onMutate: props?.onMutate,
    onSettled: props?.onSettled,
    onSuccess: props?.onSuccess,
  })

  const signMessage = (args?: SignMessageArgs) =>
    mutate(args || ({ message: props?.message } as SignMessageArgs))

  const signMessageAsync = (args?: SignMessageArgs) =>
    mutateAsync(args || ({ message: props?.message } as SignMessageArgs))

  return {
    data,
    error,
    isError,
    isIdle,
    isLoading,
    isSuccess,
    reset,
    signMessage,
    signMessageAsync,
    status,
    variables,
  }
}
