// examples/using-core/src/components/BlockNumber.tsx
import { fetchBlockNumber, watchBlockNumber } from '@wagmi/core'
import React, { useEffect, useState } from 'react'

export default function BlockNumber() {
  const [blockNumber, setBlockNumber] = useState<number | undefined>()

  useEffect(() => {
    ;(async () => {
      setBlockNumber(await fetchBlockNumber())
      const unwatch = watchBlockNumber(setBlockNumber)
      return unwatch
    })()
  }, [])

  return <div>Block number: {blockNumber}</div>
}

// playgrounds/vite-vue/src/components/BlockNumber.vue
<script setup lang="ts">
import { useBlockNumber } from '@wagmi/vue'
import { ref } from 'vue'

const watchBlockNumber = ref(false)

const { data: blockNumber } = useBlockNumber({ watch: watchBlockNumber })
</script>

<template>
  <h2>Block Number</h2>

  <div>{{ blockNumber }}</div>
  <button type="button" @click="watchBlockNumber = !watchBlockNumber">
    {{ watchBlockNumber ? 'Stop' : 'Start' }} watching
  </button>
</template>
