// packages/create-wagmi/templates/vite-react/default/src/components/SendTransaction.tsx
import { parseEther } from 'viem'
import { useSendTransaction, useWaitForTransaction } from 'wagmi'

import { stringify } from '../utils/stringify'

export function SendTransaction() {
  const { data, error, isLoading, isError, sendTransaction } =
    useSendTransaction()
  const {
    data: receipt,
    isLoading: isPending,
    isSuccess,
  } = useWaitForTransaction({ hash: data?.hash })

  return (
    <>
      <form
        onSubmit={(e) => {
          e.preventDefault()
          const formData = new FormData(e.target as HTMLFormElement)
          const address = formData.get('address') as string
          const value = formData.get('value') as `${number}`
          sendTransaction({
            to: address,
            value: parseEther(value),
          })
        }}
      >
        <input name="address" placeholder="address" />
        <input name="value" placeholder="value (ether)" />
        <button type="submit">Send</button>
      </form>

      {isLoading && <div>Check wallet...</div>}
      {isPending && <div>Transaction pending...</div>}
      {isSuccess && (
        <>
          <div>Transaction Hash: {data?.hash}</div>
          <div>
            Transaction Receipt: <pre>{stringify(receipt, null, 2)}</pre>
          </div>
        </>
      )}
      {isError && <div>Error: {error?.message}</div>}
    </>
  )
}

// playgrounds/vite-vue/src/components/SendTransaction.vue
<script setup lang="ts">
import { Hex, parseEther } from 'viem'
import { useSendTransaction } from '@wagmi/vue'

const {
  data: hash,
  error,
  isPending,
  sendTransaction
} = useSendTransaction()

function onSubmit(event: any) {
  const form = new FormData(event.target)
  const to = form.get('address')! as Hex
  const value = parseEther(form.get('value') as string)
  sendTransaction({ to, value })
}
</script>

<template>
  <h2>
    Send Transaction
  </h2>
  <form @submit.prevent="onSubmit">
    <input name="address" placeholder="Address" required />
    <input name="value" placeholder="Amount (ETH)" type="number" step="0.000000001" required />
    <button type="submit">
      Send
    </button>
  </form>
  <div v-if="isPending">
    Sending...
  </div>
  <div v-if="hash">
    Hash: {{ hash }}
  </div>
  <div v-if="error">
    Error: {{ error.message }}
  </div>
</template>
