// playgrounds/vite-solid/src/components/SwitchConnection.tsx
import {
  useConnection,
  useConnections,
  useSwitchConnection,
} from '@wagmi/solid'
import { For } from 'solid-js'

export function SwitchConnection() {
  const connection = useConnection()
  const { mutate: switchConnection } = useSwitchConnection()
  const connections = useConnections()

  return (
    <div>
      <h2>Switch Connection</h2>

      <For each={connections()}>
        {(conn) => (
          <button
            disabled={connection().connector?.uid === conn.connector.uid}
            onClick={() => switchConnection({ connector: conn.connector })}
            type="button"
          >
            {conn.connector.name}
          </button>
        )}
      </For>
    </div>
  )
}

// playgrounds/vite-vue/src/components/SwitchConnection.vue
<script setup lang="ts">
import { useConnection, useConnections, useSwitchConnection } from '@wagmi/vue'

const { connector: currentConnector } = useConnection()
const switchConnection = useSwitchConnection()
const connections = useConnections()
</script>

<template>
  <h2>Switch Connection</h2>

  <button v-for="connection in connections" :key="connection.connector.id" :disabled="currentConnector?.uid === connection.connector.uid"
    type="button" @click="switchConnection.mutate({ connector: connection.connector })">
    {{ connection.connector.name }}
  </button>

  <div>
    {{ switchConnection.status }}
    {{ switchConnection.error }}
  </div>
</template>
