// packages/create-wagmi/templates/vite-react/default/src/components/WriteContract.tsx
import { BaseError } from 'viem'
import { useContractWrite, useWaitForTransaction } from 'wagmi'

import { wagmiContractConfig } from './contracts'
import { stringify } from '../utils/stringify'

export function WriteContract() {
  const { write, data, error, isLoading, isError } = useContractWrite({
    ...wagmiContractConfig,
    functionName: 'mint',
  })
  const {
    data: receipt,
    isLoading: isPending,
    isSuccess,
  } = useWaitForTransaction({ hash: data?.hash })

  return (
    <>
      <h3>Mint a wagmi</h3>
      <form
        onSubmit={(e) => {
          e.preventDefault()
          const formData = new FormData(e.target as HTMLFormElement)
          const tokenId = formData.get('tokenId') as string
          write({
            args: [BigInt(tokenId)],
          })
        }}
      >
        <input name="tokenId" placeholder="token id" />
        <button disabled={isLoading} type="submit">
          Mint
        </button>
      </form>

      {isLoading && <div>Check wallet...</div>}
      {isPending && <div>Transaction pending...</div>}
      {isSuccess && (
        <>
          <div>Transaction Hash: {data?.hash}</div>
          <div>
            Transaction Receipt: <pre>{stringify(receipt, null, 2)}</pre>
          </div>
        </>
      )}
      {isError && <div>{(error as BaseError)?.shortMessage}</div>}
    </>
  )
}

// playgrounds/vite-vue/src/components/WriteContract.vue
<script setup lang="ts">
import { BaseError, useWriteContract } from '@wagmi/vue'
import { parseAbi } from 'viem'

const { data: hash, error, isPending, writeContract } = useWriteContract()

function submit(e: any) {
  const formData = new FormData(e.target as HTMLFormElement)
  const tokenId = formData.get('tokenId') as string
  writeContract({
    address: '0xFBA3912Ca04dd458c843e2EE08967fC04f3579c2',
    abi: parseAbi(['function mint(uint256 tokenId)']),
    functionName: 'mint',
    args: [BigInt(tokenId)],
  })
}
</script>

<template>
  <h2>Write Contract</h2>

  <form @submit.prevent="submit">
    <input name="tokenId" placeholder="Token ID" required />
    <button :disabled="isPending">Mint</button>
  </form>
  <div v-if="hash">Transaction Hash: {{ hash }}</div>
  <div v-if="error">Error: {{ (error as BaseError).shortMessage || error.message }}</div>
</template>
