// examples/next/src/components/Account.tsx
import { useAccount, useEnsName } from 'wagmi'

export function Account() {
  const { data: accountData } = useAccount()
  const { data: ensNameData } = useEnsName({ address: accountData?.address })

  return (
    <div>
      {ensNameData ?? accountData?.address}
      {ensNameData ? ` (${accountData?.address})` : null}
    </div>
  )
}

// playgrounds/sveltekit/src/routes/_components/Account.svelte
<script lang="ts">
import { useAccount } from '@wagmi/svelte'
import { useDisconnect } from '@wagmi/svelte'
import { useEnsName } from '@wagmi/svelte'

const account = $derived.by(useAccount())
const { disconnect } = $derived.by(useDisconnect())
const { data: ensName } = $derived.by(
  useEnsName(() => ({
    address: account.address,
  })),
)
</script>

<div>
	<h2>Account</h2>

	<div>
		account: {account.address}
		{ensName}
		<br />
		chainId: {account.chainId}
		<br />
		status: {account.status}
	</div>

	{#if account.status !== 'disconnected'}
		<button type="button" onclick={() => disconnect()}> Disconnect </button>
	{/if}
</div>
