// packages/create-wagmi/templates/nuxt/components/Connect.vue
<script setup lang="ts">
import { useChainId, useConnect, useConnectors } from '@wagmi/vue'

const chainId = useChainId()
const { connect, error, status } = useConnect()
const connectors = useConnectors()
</script>

<template>
  <h2>Connect</h2>

  <button v-for="connector in connectors" :key="connector.id" type="button" @click="connect({ connector, chainId })">
    {{ connector.name }}
  </button>

  <div>
    {{ status }}
    {{ error?.message }}
  </div>
</template>

// playgrounds/sveltekit/src/routes/_components/Connect.svelte
<script lang="ts">
import { useChainId } from '@wagmi/svelte'
import { useConnect } from '@wagmi/svelte'

const chainId = $derived.by(useChainId())
const { connectors, connect, status, error } = $derived.by(useConnect())
</script>

<div>
	<h2>Connect</h2>
	{#each connectors as connector (connector.uid)}
		<button onclick={() => connect({ connector, chainId })} type="button">
			{connector.name}
		</button>
	{/each}
	<div>{status}</div>
	<div>{error?.message}</div>
</div>
