// playgrounds/vite-vue/src/components/SwitchAccount.vue
<script setup lang="ts">
import { useAccount, useSwitchAccount } from '@wagmi/vue'

const { connector: currentConnector } = useAccount()
const { connectors, error, status, switchAccount } = useSwitchAccount()
</script>

<template>
  <h2>Switch Account</h2>

  <button v-for="connector in connectors" :key="connector.id" :disabled="currentConnector?.uid === connector.uid"
    type="button" @click="switchAccount({ connector })">
    {{ connector.name }}
  </button>

  <div>
    {{ status }}
    {{ error }}
  </div>
</template>

// playgrounds/sveltekit/src/routes/_components/SwitchAccount.svelte
<script lang="ts">
import { useAccount } from '@wagmi/svelte'
import { useSwitchAccount } from '@wagmi/svelte'

const account = $derived.by(useAccount())
const { connectors, switchAccount } = $derived.by(useSwitchAccount())
</script>

<h2>Switch Account</h2>

{#each connectors as connector}
	<button
		disabled={account.connector?.uid === connector.uid}
		onclick={() => switchAccount({ connector })}
		type="button"
	>
		{connector.name}
	</button>
{/each}
