// packages/create-wagmi/templates/vite-vue/src/components/Account.vue
<script setup lang="ts">
import { useAccount, useDisconnect } from "@wagmi/vue";

const { address, chainId, status } = useAccount();
const { disconnect } = useDisconnect();
</script>

<template>
  <h2>Account</h2>

  <div>
    account: {{ address }}
    <br />
    chainId: {{ chainId }}
    <br />
    status: {{ status }}
  </div>

  <button v-if="status !== 'disconnected'" type="button" @click="disconnect()">
    Disconnect
  </button>
</template>

// examples/vite-react/src/components/Account.tsx
import { useAccount } from 'wagmi'

export function Account() {
  const { data, disconnect } = useAccount({ ens: true })

  if (!data) return <div>No account connected</div>

  return (
    <div>
      <div>
        <button onClick={() => disconnect()}>
          Disconnect from {data?.connector?.name}
        </button>
      </div>

      <div>
        {data?.ens?.name ?? data?.address}
        {data?.ens ? ` (${data?.address})` : null}
      </div>

      {data?.ens?.avatar && (
        <img src={data.ens.avatar} style={{ height: 40, width: 40 }} />
      )}
    </div>
  )
}
