// packages/create-wagmi/templates/vite-react/default/src/main.tsx
import * as React from 'react'
import * as ReactDOM from 'react-dom/client'
import { WagmiConfig } from 'wagmi'

import { App } from './App'
import { config } from './wagmi'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <WagmiConfig config={config}>
      <App />
    </WagmiConfig>
  </React.StrictMode>,
)

// examples/solid/src/index.tsx
/* @refresh reload */
import {
  WagmiConfig,
  configureChains,
  createClient,
  goerli,
  mainnet,
  publicProvider,
} from '@wagmi/solid'
import { render } from 'solid-js/web'

import App from './App'

const { provider, webSocketProvider } = configureChains(
  [mainnet, goerli],
  [publicProvider()],
)

const client = createClient({
  autoConnect: true,
  provider,
  webSocketProvider,
})

render(
  () => (
    <WagmiConfig client={client}>
      <App />{' '}
    </WagmiConfig>
  ),
  document.getElementById('root') as HTMLElement,
)
