// solid-no-bun/solid/src/context.tsx
'use client'

import { type ResolvedRegister, type State } from '@wagmi/core'
import { Hydrate } from './hydrate.ts'
import { createSignal, type ParentProps } from 'solid-js'

export type WagmiProviderProps = {
  config: ResolvedRegister['config']
  initialState?: State | undefined
  reconnectOnMount?: boolean | undefined
}

export const [config, setConfig] = createSignal()

export function WagmiProvider(
  parameters: ParentProps<WagmiProviderProps>,
) {
  setConfig(parameters.config)
  return <Hydrate {...parameters} />
}

// packages/react/src/context.ts
'use client'

import type { ResolvedRegister, State } from '@wagmi/core'
import { createContext, createElement } from 'react'
import { Hydrate } from './hydrate.js'

export const WagmiContext = createContext<
  ResolvedRegister['config'] | undefined
>(undefined)

export type WagmiProviderProps = {
  config: ResolvedRegister['config']
  initialState?: State | undefined
  reconnectOnMount?: boolean | undefined
}

export function WagmiProvider(
  parameters: React.PropsWithChildren<WagmiProviderProps>,
) {
  const { children, config } = parameters

  const props = { value: config }
  return createElement(
    Hydrate,
    parameters,
    createElement(WagmiContext.Provider, props, children),
  )
}
