// packages/solid/src/hydrate.tsx
import { type ResolvedRegister, type State, hydrate } from '@wagmi/core'
import { type ParentProps, createEffect, mergeProps, onCleanup } from 'solid-js'

export type HydrateProps = {
  config: ResolvedRegister['config']
  initialState?: State | undefined
  reconnectOnMount?: boolean | undefined
}

export function Hydrate(props: ParentProps<HydrateProps>) {
  const finalProps = mergeProps({ reconnectOnMount: true }, props)

  const { onMount } = hydrate(finalProps.config, {
    initialState: finalProps.initialState,
    reconnectOnMount: finalProps.reconnectOnMount,
  })

  // Hydrate for non-SSR
  if (!finalProps.config._internal.ssr) onMount()

  // Hydrate for SSR
  let active = true
  createEffect(() => {
    if (!active) return
    if (!finalProps.config._internal.ssr) return
    onMount()
    onCleanup(() => {
      active = false
    })
  })

  return <>{finalProps.children}</>
}

// packages/react/src/hydrate.ts
'use client'

import { type ResolvedRegister, type State, hydrate } from '@wagmi/core'
import { useEffect, useRef } from 'react'

export type HydrateProps = {
  config: ResolvedRegister['config']
  initialState?: State | undefined
  reconnectOnMount?: boolean | undefined
}

export function Hydrate(parameters: React.PropsWithChildren<HydrateProps>) {
  const { children, config, initialState, reconnectOnMount = true } = parameters

  const { onMount } = hydrate(config, {
    initialState,
    reconnectOnMount: reconnectOnMount,
  })

  // Hydrate for non-SSR
  if (!config._internal.ssr) onMount()

  // Hydrate for SSR
  const active = useRef(true)
  // biome-ignore lint/nursery/useExhaustiveDependencies:
  useEffect(() => {
    if (!active.current) return
    if (!config._internal.ssr) return
    onMount()
    return () => {
      active.current = false
    }
  }, [])

  return children
}
