// playgrounds/sveltekit/src/routes/_components/SignMessage.svelte
<script lang="ts">
import { useSignMessage } from '@wagmi/svelte'
import type { SignableMessage } from 'viem'

const { data, signMessage } = $derived.by(useSignMessage())

function handleSubmit(event: SubmitEvent) {
  event.preventDefault()
  const formData = new FormData(event.target as HTMLFormElement)
  signMessage({ message: formData.get('message') as SignableMessage })
}
</script>

<h2>Sign Message</h2>

<form onsubmit={handleSubmit}>
	<input name="message" />
	<button type="submit">Sign Message</button>
</form>

{#if data}
	{data}
{/if}

// packages/create-wagmi/templates/vite-react/default/src/components/SignMessage.tsx
import { useEffect, useState } from 'react'
import { recoverMessageAddress } from 'viem'
import { type Address, useSignMessage } from 'wagmi'

export function SignMessage() {
  const [recoveredAddress, setRecoveredAddress] = useState<Address>()
  const {
    data: signature,
    variables,
    error,
    isLoading,
    signMessage,
  } = useSignMessage()

  useEffect(() => {
    ;(async () => {
      if (variables?.message && signature) {
        const recoveredAddress = await recoverMessageAddress({
          message: variables?.message,
          signature,
        })
        setRecoveredAddress(recoveredAddress)
      }
    })()
  }, [signature, variables?.message])

  return (
    <>
      <form
        onSubmit={(event) => {
          event.preventDefault()
          const element = event.target as HTMLFormElement
          const formData = new FormData(element)
          const message = formData.get('message') as string
          signMessage({ message })
        }}
      >
        <input name="message" type="text" required />
        <button disabled={isLoading} type="submit">
          {isLoading ? 'Check Wallet' : 'Sign Message'}
        </button>
      </form>

      {signature && (
        <div>
          <div>Signature: {signature}</div>
          <div>Recovered address: {recoveredAddress}</div>
        </div>
      )}
      {error && <div>Error: {error?.message}</div>}
    </>
  )
}
