// playgrounds/vite-vue/src/components/Connection.vue
<script setup lang="ts">
import { useConnection, useDisconnect } from '@wagmi/vue'

const { address, chainId, status } = useConnection()
const disconnect = useDisconnect()
</script>

<template>
  <h2>Connection</h2>

  <div>
    address: {{ address }}
    <br />
    chainId: {{ chainId }}
    <br />
    status: {{ status }}
  </div>

  <button v-if="status !== 'disconnected'" type="button" @click="disconnect.mutate()">
    Disconnect
  </button>
</template>

// playgrounds/solid-start/src/components/Connection.tsx
import { useConnection, useDisconnect } from '@wagmi/solid'
import { Show } from 'solid-js'

export function Connection() {
  const connection = useConnection()
  const disconnect = useDisconnect()

  return (
    <div>
      <h2>Connection</h2>

      <div>
        account: {connection().address}
        <br />
        chainId: {connection().chainId}
        <br />
        status: {connection().status}
      </div>

      <Show when={connection().status !== 'disconnected'}>
        <button
          type="button"
          onClick={() => {
            console.log('disconnect clicked')
            disconnect.mutate()
          }}
        >
          Disconnect
        </button>
      </Show>
    </div>
  )
}
