// playgrounds/vite-vue/src/components/SwitchChain.vue
<script setup lang="ts">
import { useChainId, useChains, useSwitchChain } from '@wagmi/vue'

const chainId = useChainId()
const switchChain = useSwitchChain()
const chains = useChains()
</script>

<template>
  <h2>Switch Chain</h2>

  <div>Chain ID: {{ chainId }}</div>

  <button v-for="chain in chains" :key="chain.id" :disabled="chain.id === chainId" type="button"
    @click="switchChain.mutate({ chainId: chain.id })">
    {{ chain.name }}
  </button>

  <div>
    {{ switchChain.status }}
    {{ switchChain.error }}
  </div>
</template>

// playgrounds/solid-start/src/components/SwitchChain.tsx
import { useChainId, useChains, useSwitchChain } from '@wagmi/solid'
import { For } from 'solid-js'

export function SwitchChain() {
  const chainId = useChainId()
  const switchChain = useSwitchChain()
  const chains = useChains()

  return (
    <div>
      <h2>Switch Chain</h2>

      <For each={chains()}>
        {(chain) => (
          <button
            disabled={chainId() === chain.id}
            onClick={() => switchChain.mutate({ chainId: chain.id })}
            type="button"
          >
            {chain.name}
          </button>
        )}
      </For>

      {switchChain.error?.message}
    </div>
  )
}
