// examples/vite-react/src/App.tsx
import { useAccount, useConnect } from 'wagmi'

export const App = () => {
  const account = useAccount({ fetchEns: true })
  // console.log(account)

  const connect = useConnect()
  const connect2 = useConnect()
  // console.log({ connect, connect2 })
  // console.log(connect)

  if (account.data?.address)
    return (
      <div>
        <div>{account.data.address}</div>
        <button onClick={account.disconnect}>disconnect</button>
      </div>
    )

  return (
    <div>
      {account.data?.address}
      <div>
        <h3>connect 1</h3>
        <div>
          {connect.connectors.map((x) => (
            <button
              disabled={!x.ready || connect.isConnecting}
              key={x.name}
              onClick={() => connect.connect(x)}
            >
              {x.name}
              {connect.isConnecting && x.id === connect.connector?.id && '…'}
            </button>
          ))}
        </div>
        <div>
          {connect.error && (connect.error?.message ?? 'Failed to connect')}
        </div>
      </div>

      <div>
        <h3>connect 2</h3>
        <div>
          {connect2.connectors.map((x) => (
            <button
              disabled={!x.ready || connect2.isConnecting}
              key={x.name}
              onClick={() => connect2.connect(x)}
            >
              {x.name}
              {connect2.isConnecting && x.id === connect2.connector?.id && '…'}
            </button>
          ))}
        </div>
        <div>
          {connect2.error && (connect2.error?.message ?? 'Failed to connect')}
        </div>
      </div>
    </div>
  )
}

// playgrounds/vite-vue/src/App.vue
<script setup lang="ts">
  import { useAccount, useConnect, useDisconnect } from '@wagmi/vue'

  const account = useAccount()
  const connect = useConnect()
  const disconnect = useDisconnect()
</script>

<template>
  <div>
    <div>
      <h2>Account</h2>

      <div>
        account: {{ account.address }}
        <br />
        chainId: {{ account.chainId }}
        <br />
        status: {{ account.status }}
      </div>

      <button
        v-if="account.status !== 'disconnected'"
        type="button"
        @click="disconnect.disconnect()"
      >
        Disconnect
      </button>
    </div>

    <div>
      <h2>Connect</h2>

      <button
        v-for="connector in connect.connectors"
        :key="connector.id"
        type="button"
        @click="connect.connect({ connector })"
      >
        {{ connector.name }}
      </button>

      <div>{{ connect.status }}</div>
      <div>{{ connect.error }}</div>
    </div>
  </div>
</template>
