// playgrounds/vite-solid/src/App.tsx
import { Balance } from './components/Balance'
import { BlockNumber } from './components/BlockNumber'
import { Connect } from './components/Connect'
import { Connection } from './components/Connection'
import { Connections } from './components/Connections'
import { ConnectorClient } from './components/ConnectorClient'
import { SwitchChain } from './components/SwitchChain'
import { SwitchConnection } from './components/SwitchConnection'

function App() {
  return (
    <>
      <Connection />
      <Connect />
      <SwitchConnection />
      <SwitchChain />
      {/* <SignMessage /> */}
      <Connections />
      <BlockNumber />
      <Balance />
      <ConnectorClient />
      {/* <SendTransaction /> */}
      {/* <ReadContract /> */}
      {/* <ReadContracts /> */}
      {/* <WriteContract /> */}
    </>
  )
}

export default App

// playgrounds/vite-vue/src/App.vue
<script setup lang="ts">
import Account from './components/Account.vue'
import Balance from './components/Balance.vue'
import BlockNumber from './components/BlockNumber.vue'
import Client from './components/Client.vue'
import Connect from './components/Connect.vue'
import Connections from './components/Connections.vue'
import ConnectorClient from './components/ConnectorClient.vue'
import ReadContract from './components/ReadContract.vue'
import SendTransaction from './components/SendTransaction.vue'
import SwitchAccount from './components/SwitchAccount.vue'
import SwitchChain from './components/SwitchChain.vue'
import WatchEvent from './components/WatchEvent.vue'
import WriteContract from './components/WriteContract.vue'
</script>

<template>
  <Account />
  <Balance />
  <Connect />
  <Connections />
  <SwitchAccount />
  <SwitchChain />
  <BlockNumber />
  <ReadContract />
  <SendTransaction />
  <WatchEvent />
  <WriteContract />
  <Client />
  <ConnectorClient />
</template>
