// packages/react/src/context.tsx
import { Provider, WebSocketProvider } from '@wagmi/core'
import * as React from 'react'
import { QueryClientProvider } from 'react-query'

import { Client } from './client'

export const Context = React.createContext<
  Client<Provider, WebSocketProvider> | undefined
>(undefined)

export type WagmiConfigProps<
  TProvider extends Provider = Provider,
  TWebSocketProvider extends WebSocketProvider = WebSocketProvider,
> = {
  /** React-decorated Client instance */
  client: Client<TProvider, TWebSocketProvider>
}
export function WagmiConfig<
  TProvider extends Provider,
  TWebSocketProvider extends WebSocketProvider,
>({
  children,
  client,
}: React.PropsWithChildren<WagmiConfigProps<TProvider, TWebSocketProvider>>) {
  return (
    <Context.Provider value={client as unknown as Client}>
      <QueryClientProvider client={client.queryClient}>
        {children}
      </QueryClientProvider>
    </Context.Provider>
  )
}

export function useClient<
  TProvider extends Provider,
  TWebSocketProvider extends WebSocketProvider = WebSocketProvider,
>() {
  const client = React.useContext(Context) as unknown as Client<
    TProvider,
    TWebSocketProvider
  >
  if (!client)
    throw new Error(
      [
        '`useClient` must be used within `WagmiConfig`.\n',
        'Read more: https://wagmi.sh/docs/WagmiConfig',
      ].join('\n'),
    )
  return client
}

// packages/solid/src/context.tsx
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query'
import type { Provider, WebSocketProvider } from '@wagmi/core'
import { createContext, useContext } from 'solid-js'
import type { ParentProps } from 'solid-js'

import type { Client } from './client'

export const Context = createContext<
  Client<Provider, WebSocketProvider> | undefined
>(undefined)

const queryClient = new QueryClient()

export type WagmiConfigProps<
  TProvider extends Provider = Provider,
  TWebSocketProvider extends WebSocketProvider = WebSocketProvider,
> = {
  /** React-decorated Client instance */
  client: Client<TProvider, TWebSocketProvider>
  queryClient?: QueryClient
}
export function WagmiProvider<
  TProvider extends Provider,
  TWebSocketProvider extends WebSocketProvider,
>(props: ParentProps<WagmiConfigProps<TProvider, TWebSocketProvider>>) {
  return (
    <QueryClientProvider client={props.client.queryClient ?? queryClient}>
      <Context.Provider value={props.client as any}>
        {props.children}
      </Context.Provider>
    </QueryClientProvider>
  )
}

export function useClient<
  TProvider extends Provider,
  TWebSocketProvider extends WebSocketProvider = WebSocketProvider,
>() {
  const client = useContext(Context) as unknown as Client<
    TProvider,
    TWebSocketProvider
  >
  if (!client)
    throw new Error(
      [
        '`useClient` must be used within `WagmiConfig`.\n',
        'Read more: https://wagmi.sh/solid/WagmiConfig',
      ].join('\n'),
    )
  return client
}
