// packages/react/src/context.ts
'use client'

import type { ResolvedRegister, State } from '@wagmi/core'
import { createContext, createElement } from 'react'
import { Hydrate } from './hydrate.js'

export const WagmiContext = createContext<
  ResolvedRegister['config'] | undefined
>(undefined)

export type WagmiProviderProps = {
  config: ResolvedRegister['config']
  initialState?: State | undefined
  reconnectOnMount?: boolean | undefined
}

export function WagmiProvider(
  parameters: React.PropsWithChildren<WagmiProviderProps>,
) {
  const { children, config } = parameters

  const props = { value: config }
  return createElement(
    Hydrate,
    parameters,
    createElement(WagmiContext.Provider, props, children),
  )
}

// packages/solid/src/context.tsx
import type { ResolvedRegister } from '@wagmi/core'
import { type ParentProps, createContext } from 'solid-js'

import { Hydrate } from './hydrate.jsx'

export const WagmiContext = createContext<
  ResolvedRegister['config'] | undefined
>(undefined)

export type WagmiProviderProps = {
  config: ResolvedRegister['config']
  // initialState?: State | undefined
  reconnectOnMount?: boolean | undefined
}

export function WagmiProvider(props: ParentProps<WagmiProviderProps>) {
  return (
    <Hydrate {...props}>
      <WagmiContext.Provider value={props.config}>
        {props.children}
      </WagmiContext.Provider>
    </Hydrate>
  )
}
