// packages/react/src/hydrate.ts
'use client'

import { type ResolvedRegister, type State, hydrate } from '@wagmi/core'
import { type ReactElement, useEffect, useRef } from 'react'

export type HydrateProps = {
  config: ResolvedRegister['config']
  initialState?: State | undefined
  reconnectOnMount?: boolean | undefined
}

export function Hydrate(parameters: React.PropsWithChildren<HydrateProps>) {
  const { children, config, initialState, reconnectOnMount = true } = parameters

  const { onMount } = hydrate(config, {
    initialState,
    reconnectOnMount,
  })

  // Hydrate for non-SSR
  if (!config._internal.ssr) onMount()

  // Hydrate for SSR
  // biome-ignore lint/nursery/useExhaustiveDependencies:
  useEffect(() => {
    if (!config._internal.ssr) return
    onMount()
  }, [onMount])

  return children as ReactElement
}

// packages/solid/src/hydrate.ts
import { hydrate, type ResolvedRegister, type State } from '@wagmi/core'
import { mergeProps, onMount, type ParentProps } from 'solid-js'

export type HydrateProps = {
  config: ResolvedRegister['config']
  initialState?: State | undefined
  reconnectOnMount?: boolean | undefined
}

export function Hydrate(parameters: ParentProps<HydrateProps>) {
  const props = mergeProps({ reconnectOnMount: true }, parameters)

  const { onMount: hydrateOnMount } = hydrate(props.config, {
    initialState: props.initialState,
    reconnectOnMount: props.reconnectOnMount,
  })

  // Hydrate for non-SSR
  if (!props.config._internal.ssr) hydrateOnMount()

  onMount(() => {
    if (!props.config._internal.ssr) return
    hydrateOnMount()
  })

  return props.children
}
