// playgrounds/vite-react/src/main.tsx
import { Buffer } from 'buffer'
import { createSyncStoragePersister } from '@tanstack/query-sync-storage-persister'
import { QueryClient } from '@tanstack/react-query'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { PersistQueryClientProvider } from '@tanstack/react-query-persist-client'
import React from 'react'
import ReactDOM from 'react-dom/client'
import { WagmiProvider, deserialize, serialize } from 'wagmi'

import './index.css'

// `@coinbase-wallet/sdk` uses `Buffer`
globalThis.Buffer = Buffer

import App from './App.tsx'
import { config } from './wagmi.ts'

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      gcTime: 1_000 * 60 * 60 * 24, // 24 hours
      networkMode: 'offlineFirst',
      refetchOnWindowFocus: false,
      retry: 0,
    },
    mutations: { networkMode: 'offlineFirst' },
  },
})

const persister = createSyncStoragePersister({
  key: 'vite-react.cache',
  serialize,
  storage: window.localStorage,
  deserialize,
})

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <WagmiProvider config={config}>
      <PersistQueryClientProvider
        client={queryClient}
        persistOptions={{ persister }}
      >
        <App />
        <ReactQueryDevtools initialIsOpen={false} />
      </PersistQueryClientProvider>
    </WagmiProvider>
  </React.StrictMode>,
)

// solid-no-bun/playground/vite-solid/src/index.tsx
/* @refresh reload */
import { render } from 'solid-js/web'
import './index.css'
import App from './App'

import { Buffer } from 'buffer'
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query'
import { WagmiProvider } from 'solid-wagmi'
import { config } from './wagmi.js'

// `@coinbase-wallet/sdk` uses `Buffer`
window.Buffer = Buffer

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      gcTime: 1_000 * 60 * 60 * 24, // 24 hours
      networkMode: 'offlineFirst',
      refetchOnWindowFocus: false,
      retry: 0,
    },
    mutations: { networkMode: 'offlineFirst' },
  },
})

const root = document.getElementById('root')

render(() =>(
  <WagmiProvider config={config}>
    <QueryClientProvider client={queryClient}>
    <App />
    </QueryClientProvider>
  </WagmiProvider>
  ), root!)

  declare global {
    interface Window {
      Buffer?: unknown
    }
  }
