// packages/svelte/src/routes/_components/Account.svelte
<script lang="ts">
import { useAccount } from '$lib/hooks/useAccount.svelte.js'

const account = $derived.by(useAccount())
// const { disconnect } = $derived.by(useDisconnect())
// const { data: ensName } = $derived.by(useEnsName({
//   address: account.address,
// }))
</script>

  <div>
    <h2>Account</h2>

    <div>
      account: {account.address}
      <!-- {ensName} -->
      <br />
      chainId: {account.chainId}
      <br />
      status: {account.status}
    </div>

    <!-- {#if account.status !== 'disconnected'}
      <button type="button" onClick={() => disconnect()}>
        Disconnect
      </button>
    {/if} -->
  </div>

// packages/create-wagmi/templates/vite-vue/src/components/Account.vue
<script setup lang="ts">
import { useAccount, useDisconnect } from "@wagmi/vue";

const { address, chainId, status } = useAccount();
const { disconnect } = useDisconnect();
</script>

<template>
  <h2>Account</h2>

  <div>
    account: {{ address }}
    <br />
    chainId: {{ chainId }}
    <br />
    status: {{ status }}
  </div>

  <button v-if="status !== 'disconnected'" type="button" @click="disconnect()">
    Disconnect
  </button>
</template>
