// examples/vite-react/src/components/Connect.tsx
import { useConnect } from 'wagmi'

export const Connect = () => {
  const [{ connector, connectors, error, loading }, connect] = useConnect()

  return (
    <>
      <div>
        {connectors.map((x) => (
          <button key={x.name} onClick={() => connect(x)}>
            {x.name}
            {loading && x.name === connector?.name && '…'}
          </button>
        ))}
      </div>
      <div>{error && (error?.message ?? 'Failed to connect')}</div>
    </>
  )
}

// packages/create-wagmi/templates/vite-vue/src/components/Connect.vue
<script setup lang="ts">
import { useChainId, useConnect } from "@wagmi/vue";

const chainId = useChainId();
const { connect, connectors, error, status } = useConnect();
</script>

<template>
  <h2>Connect</h2>

  <button v-for="connector in connectors" :key="connector.id" type="button" @click="connect({ connector, chainId })">
    {{ connector.name }}
  </button>

  <div>
    {{ status }}
    {{ error?.message }}
  </div>
</template>
