// playgrounds/next/src/app/providers.tsx
'use client'

import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { type ReactNode, useState } from 'react'
import { WagmiProvider } from 'wagmi'

import { config } from '../wagmi'

export function Providers(props: { children: ReactNode }) {
  const [queryClient] = useState(() => new QueryClient())

  return (
    <WagmiProvider config={config}>
      <QueryClientProvider client={queryClient}>
        {props.children}
      </QueryClientProvider>
    </WagmiProvider>
  )
}

// packages/devtools-ui/src/components/Providers.tsx
import { QueryClientProvider } from '@tanstack/solid-query'
import { WagmiProvider } from '@wagmi/solid'
import type { ParentProps } from 'solid-js'

import { useDevtoolsContext } from '../context.js'

export function Providers(props: Providers.Props) {
  const value = useDevtoolsContext()
  return (
    <WagmiProvider config={value.config}>
      <QueryClientProvider client={value.queryClient}>
        {props.children}
      </QueryClientProvider>
    </WagmiProvider>
  )
}

export declare namespace Providers {
  export type Props = ParentProps
}
