// playgrounds/vite-solid/src/index.tsx
/* @refresh reload */

import { QueryClient, QueryClientProvider } from '@tanstack/solid-query'
import { WagmiProvider } from '@wagmi/solid'
import { Buffer } from 'buffer'
import { render } from 'solid-js/web'

import './index.css'

// `@coinbase-wallet/sdk` uses `Buffer`
globalThis.Buffer = Buffer

import App from './App.tsx'
import { config } from './wagmi.ts'

const queryClient = new QueryClient()

const root = document.getElementById('root')

render(
  () => (
    <WagmiProvider config={config}>
      <QueryClientProvider client={queryClient}>
        <App />
      </QueryClientProvider>
    </WagmiProvider>
  ),
  root!,
)

// playgrounds/vite-core/src/main.tsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import './index.css'

import { Buffer } from 'buffer'

// `@coinbase-wallet/sdk` uses `Buffer`
globalThis.Buffer = Buffer

import App from './App.tsx'

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
