// packages/solid/src/primitives/useChains.ts
import {
  type Config,
  type GetChainsReturnType,
  getChains,
  type ResolvedRegister,
} from '@wagmi/core'
import { watchChains } from '@wagmi/core/internal'

import { type Accessor, createEffect, createSignal, onCleanup } from 'solid-js'
import type { ConfigParameter } from '../types/properties.js'
import { useConfig } from './useConfig.js'

export type SolidChainsParameters<config extends Config = Config> =
  ConfigParameter<config>

export type UseChainsParameters<config extends Config = Config> = Accessor<
  ConfigParameter<config>
>

export type SolidChainsReturnType<config extends Config = Config> =
  GetChainsReturnType<config>

export type UseChainsReturnType<config extends Config = Config> = Accessor<
  GetChainsReturnType<config>
>

/** https://wagmi.sh/solid/api/primitives/useChains */
export function useChains<config extends Config = ResolvedRegister['config']>(
  parameters: UseChainsParameters<config> = () => ({}),
): UseChainsReturnType<config> {
  const config = useConfig(parameters)

  const [chains, setChains] = createSignal<GetChainsReturnType<config>>(
    getChains(config()),
  )

  createEffect(() => {
    const unsubscribe = watchChains(config(), {
      onChange(data) {
        setChains(() => data)
      },
    })
    onCleanup(() => unsubscribe())
  })

  return chains
}

// packages/react/src/hooks/useChains.ts
'use client'

import {
  type Config,
  type GetChainsReturnType,
  getChains,
  type ResolvedRegister,
} from '@wagmi/core'
import { watchChains } from '@wagmi/core/internal'
import { useSyncExternalStore } from 'react'

import type { ConfigParameter } from '../types/properties.js'
import { useConfig } from './useConfig.js'

export type UseChainsParameters<config extends Config = Config> =
  ConfigParameter<config>

export type UseChainsReturnType<config extends Config = Config> =
  GetChainsReturnType<config>

/** https://wagmi.sh/react/api/hooks/useChains */
export function useChains<config extends Config = ResolvedRegister['config']>(
  parameters: UseChainsParameters<config> = {},
): UseChainsReturnType<config> {
  const config = useConfig(parameters)

  return useSyncExternalStore(
    (onChange) => watchChains(config, { onChange }),
    () => getChains(config),
    () => getChains(config),
  )
}
