// packages/solid/src/primitives/useChainId.ts
import {
  type Config,
  type GetChainIdReturnType,
  getChainId,
  type ResolvedRegister,
  watchChainId,
} from '@wagmi/core'
import { type Accessor, createEffect, createSignal, onCleanup } from 'solid-js'

import type { ConfigParameter } from '../types/properties.js'
import { useConfig } from './useConfig.js'

export type SolidChainIdParameters<config extends Config = Config> =
  ConfigParameter<config>

export type UseChainIdParameters<config extends Config = Config> = Accessor<
  SolidChainIdParameters<config>
>

export type UseChainIdReturnType<config extends Config = Config> = Accessor<
  GetChainIdReturnType<config>
>

/** https://wagmi.sh/solid/api/hooks/useChainId */
export function useChainId<config extends Config = ResolvedRegister['config']>(
  parameters: UseChainIdParameters<config>,
): UseChainIdReturnType<config> {
  const config = useConfig(parameters)

  const [chainId, setChainId] = createSignal(getChainId(config()))

  createEffect(() => {
    const _config = config()
    setChainId(() => getChainId(_config))

    const unsubscribe = watchChainId(_config, {
      onChange(data) {
        setChainId(() => data)
      },
    })
    onCleanup(() => unsubscribe())
  })

  return chainId
}

// packages/react/src/hooks/useChainId.ts
import {
  type Config,
  type GetChainIdReturnType,
  type ResolvedRegister,
  getChainId,
  watchChainId,
} from '@wagmi/core'
import { useSyncExternalStore } from 'react'

import type { ConfigParameter } from '../types/properties.js'
import { useConfig } from './useConfig.js'

export type UseChainIdParameters<
  config extends Config = ResolvedRegister['config'],
> = ConfigParameter<config>

export type UseChainIdReturnType<
  config extends Config = ResolvedRegister['config'],
> = GetChainIdReturnType<config>

/** https://wagmi.sh/react/hooks/useChainId */
export function useChainId<config extends Config>(
  parameters: UseChainIdParameters<config> = {},
): UseChainIdReturnType<config> {
  const config = useConfig(parameters)
  return useSyncExternalStore(
    (onChange) => watchChainId(config, { onChange }),
    () => getChainId(config),
  )
}
