// packages/solid/src/primitives/useConnect.ts
import type { Config, ConnectErrorType } from '@wagmi/core'
import type { Compute } from '@wagmi/core/internal'
import {
  type ConnectData,
  type ConnectMutate,
  type ConnectMutateAsync,
  type ConnectVariables,
  connectMutationOptions,
} from '@wagmi/core/query'
import { type Accessor, createEffect, mergeProps, onCleanup } from 'solid-js'

import type { ConfigParameter } from '../types/properties.js'
import type {
  UseMutationParameters,
  UseMutationReturnType,
} from '../utils/query.js'
import { useMutation } from '../utils/query.js'
import { useConfig } from './useConfig.js'
import { type UseConnectorsReturnType, useConnectors } from './useConnectors.js'

export type SolidConnectParameters<
  config extends Config = Config,
  context = unknown,
> = Compute<
  ConfigParameter<config> & {
    mutation?:
      | UseMutationParameters<
          ConnectData<config, config['connectors'][number], boolean>,
          ConnectErrorType,
          ConnectVariables<config, config['connectors'][number], boolean>,
          context
        >
      | undefined
  }
>

export type UseConnectParameters<
  config extends Config = Config,
  context = unknown,
> = Accessor<SolidConnectParameters<config, context>>

export type UseConnectReturnType<
  config extends Config = Config,
  context = unknown,
> = Compute<
  UseMutationReturnType<
    ConnectData<config, config['connectors'][number], boolean>,
    ConnectErrorType,
    ConnectVariables<config, config['connectors'][number], boolean>,
    context
  > & {
    /** @deprecated use `mutate` instead */
    connect: ConnectMutate<config, context>
    /** @deprecated use `mutateAsync` instead */
    connectAsync: ConnectMutateAsync<config, context>
    /** @deprecated use `useConnectors` instead */
    connectors: Compute<UseConnectorsReturnType> | config['connectors']
    mutate: ConnectMutate<config, context>
    mutateAsync: ConnectMutateAsync<config, context>
  }
>

/** https://wagmi.sh/solid/api/hooks/useConnect */
export function useConnect<config extends Config = Config, context = unknown>(
  parameters: UseConnectParameters<config, context> = () => ({}),
): UseConnectReturnType<config, context> {
  const config = useConfig(parameters)
  const connectors = useConnectors(parameters)

  const mutation = useMutation(() => {
    const mutationOptions = connectMutationOptions(config())
    return {
      ...(parameters().mutation ?? {}),
      ...mutationOptions,
    } as typeof mutationOptions
  })

  // Reset mutation back to an idle state when the connector disconnects.
  createEffect(() => {
    const unsubscribe = config().subscribe(
      ({ status }) => status,
      (status, previousStatus) => {
        if (previousStatus === 'connected' && status === 'disconnected') {
          mutation.reset()
        }
      },
    )
    onCleanup(() => unsubscribe())
  })

  type Return = UseConnectReturnType<config, context>
  return mergeProps(mutation, {
    connect: mutation.mutate,
    connectAsync: mutation.mutateAsync,
    connectors,
  }) as Return
}

// packages/react/src/hooks/useConnect.ts
'use client'

import { useMutation } from '@tanstack/react-query'
import type { Config, ConnectErrorType, ResolvedRegister } from '@wagmi/core'
import type { Compute } from '@wagmi/core/internal'
import {
  type ConnectData,
  type ConnectMutate,
  type ConnectMutateAsync,
  type ConnectVariables,
  connectMutationOptions,
} from '@wagmi/core/query'
import { useEffect } from 'react'

import type { ConfigParameter } from '../types/properties.js'
import type {
  UseMutationParameters,
  UseMutationReturnType,
} from '../utils/query.js'
import { useConfig } from './useConfig.js'
import { type UseConnectorsReturnType, useConnectors } from './useConnectors.js'

export type UseConnectParameters<
  config extends Config = Config,
  context = unknown,
> = Compute<
  ConfigParameter<config> & {
    mutation?:
      | UseMutationParameters<
          ConnectData<config, config['connectors'][number], boolean>,
          ConnectErrorType,
          ConnectVariables<config, config['connectors'][number], boolean>,
          context
        >
      | undefined
  }
>

export type UseConnectReturnType<
  config extends Config = Config,
  context = unknown,
> = Compute<
  UseMutationReturnType<
    ConnectData<config, config['connectors'][number], boolean>,
    ConnectErrorType,
    ConnectVariables<config, config['connectors'][number], boolean>,
    context
  > & {
    mutate: ConnectMutate<config, context>
    mutateAsync: ConnectMutateAsync<config, context>
    /** @deprecated use `mutate` instead */
    connect: ConnectMutate<config, context>
    /** @deprecated use `mutateAsync` instead */
    connectAsync: ConnectMutateAsync<config, context>
    /** @deprecated use `useConnectors` instead */
    connectors: Compute<UseConnectorsReturnType> | config['connectors']
  }
>

/** https://wagmi.sh/react/api/hooks/useConnect */
export function useConnect<
  config extends Config = ResolvedRegister['config'],
  context = unknown,
>(
  parameters: UseConnectParameters<config, context> = {},
): UseConnectReturnType<config, context> {
  const { mutation } = parameters

  const config = useConfig(parameters)

  const mutationOptions = connectMutationOptions(config)
  const { mutate, mutateAsync, ...result } = useMutation({
    ...(mutation as typeof mutationOptions),
    ...mutationOptions,
  })

  // Reset mutation back to an idle state when the connector disconnects.
  useEffect(() => {
    return config.subscribe(
      ({ status }) => status,
      (status, previousStatus) => {
        if (previousStatus === 'connected' && status === 'disconnected')
          result.reset()
      },
    )
  }, [config, result.reset])

  type Return = UseConnectReturnType<config, context>
  return {
    ...(result as Return),
    mutate: mutate as Return['mutate'],
    mutateAsync: mutateAsync as Return['mutateAsync'],
    connect: mutate as Return['connect'],
    connectAsync: mutateAsync as Return['connectAsync'],
    connectors: useConnectors({ config }),
  }
}
